LangString welcome ${LANG_DUTCH} "Deze wizard zal u door de installatie van ${NAME} begeleiden.\r\n\r\nIndien u een bestaande installatie wil vernieuwen van ${NAME}, sluit deze dan alstublieft af voordat u verder gaat.\r\n\r\nKlik Volgende om verder te gaan."
LangString finish ${LANG_DUTCH} "${NAME} is geinstalleerd op uw apparaat.\r\n\r\nKlik Eindigen om deze wizard te sluiten."
LangString runwarning ${LANG_DUTCH} "Sluit alstublieft alle processen van ${CLOSENAME} en klik dan op OK.  De draagbare toepassing kan niet vernieuwd worden zolang deze nog gebruikt wordt."
LangString invaliddirectory ${LANG_DUTCH} "De gekozen bestemmingsmap is ongeldig.  Kies een geldige map."
LangString notenoughspace ${LANG_DUTCH} "Het toestel dat u geselecteerd heeft, heeft onvoldoende beschikbare schijfruimte voor deze toepassing."
LangString checkforplatform ${LANG_DUTCH} "Controleert op PortableApps.com Platform"
LangString refreshmenu ${LANG_DUTCH} "Vernieuwt PortableApps.com Menu"