LangString welcome ${LANG_SIMPCHINESE} "±¾°²×°Ïòµ¼½«Òýµ¼Äú°²×° ${NAME}.\r\n\r\nÈç¹ûÄú´òËãÉý¼¶¾É°æ±¾µÄ ${NAME}, ÇëÔÚ²Ù×÷Ö®Ç°¹Ø±ÕËü.\r\n\r\nµã»÷ ÏÂÒ»²½ ¼ÌÐø."
LangString finish ${LANG_SIMPCHINESE} "${NAME} ÒÑ¾­±»°²×°µ½ÄúµÄÉè±¸ÉÏÁË.\r\n\r\nµã»÷ ½áÊø À´¹Ø±Õ±¾°²×°Ïòµ¼."
LangString runwarning ${LANG_SIMPCHINESE} "Çë¹Ø±ÕËùÓÐÓë ${CLOSENAME} Ïà¹ØµÄ³ÌÐò£¬È»ºóµã»÷ È·¶¨.  µ±PortableAppÈí¼þÔÚÔËÐÐÊ±£¬ÊÇ²»ÄÜ½øÐÐÉý¼¶µÄ."
LangString invaliddirectory ${LANG_SIMPCHINESE} "ÄúÑ¡ÔñµÄ°²×°Ä¿Â¼ÎÞÐ§£¬ÇëÑ¡ÔñÒ»¸öÓÐÐ§µÄÄ¿Â¼."
LangString notenoughspace ${LANG_SIMPCHINESE} "ÄúÑ¡ÔñµÄ°²×°Éè±¸Ã»ÓÐ×ã¹»µÄ¿Õ¼äÀ´°²×°±¾Ì×¼þ."
LangString checkforplatform ${LANG_SIMPCHINESE} "ÕýÔÚ¼ì²é PortableApps.com Æ½Ì¨"
LangString refreshmenu ${LANG_SIMPCHINESE} "ÕýÔÚ¸üÐÂ PortableApps.com ²Ëµ¥"

LangString plok ${LANG_SIMPCHINESE} "is up to date!"
LangString components ${LANG_SIMPCHINESE} "Select the components to install/update. Attention! The needed space count is only for the downloaded packages!"
LangString d_button ${LANG_SIMPCHINESE} "Browse"
LangString d_subtext ${LANG_SIMPCHINESE} "Downloaded install packages of ${NAME} (up to 200 MB depending on your selection) will be stored in this folder. If you want to use another folder, please click Browse and select another one."
LangString d_label ${LANG_SIMPCHINESE} "Save downloaded files to:"
LangString allok ${LANG_SIMPCHINESE} "All your apps are up-to-date. No updates are needed"
LangString wrongdir ${LANG_SIMPCHINESE} "Error: The installation directory has $R0 space left$R1.$\nPlease select another directory."
LangString deleteok ${LANG_SIMPCHINESE} "Do you really want to delete all files in $INSTDIR?"
LangString plswait ${LANG_SIMPCHINESE} "... a moment"
LangString db_error ${LANG_SIMPCHINESE} "Database Error$\n$UFile not found!"
LangString db_stop ${LANG_SIMPCHINESE} "Download aborted! Do you want to stop all tasks and close the updater?"
LangString self_update ${LANG_SIMPCHINESE} "A newer Updater version was downloaded. Please run setup and then start the program again."
LangString no_comp ${LANG_SIMPCHINESE} "Please select a Component or click Cancel!"
LangString op_title ${LANG_SIMPCHINESE} "PortableApps.com (TM) Updater - Options"
LangString op_text ${LANG_SIMPCHINESE} "Deselect the Controlbox Options to hide this Dialog"
LangString field1 ${LANG_SIMPCHINESE} "Proxy settings (Man. needs IP:PORT-USERNAME-PASSWORD)"
LangString field2 ${LANG_SIMPCHINESE} "Auto"
LangString field3 ${LANG_SIMPCHINESE} "None"
LangString field4 ${LANG_SIMPCHINESE} "Man."
LangString field5 ${LANG_SIMPCHINESE} "[IP:PORT]"
LangString field6 ${LANG_SIMPCHINESE} "[USERNAME]"
LangString field7 ${LANG_SIMPCHINESE} "[PASSWORD]"
LangString field8 ${LANG_SIMPCHINESE} "Updater Options"
LangString field9 ${LANG_SIMPCHINESE} "Package Location"
LangString field11 ${LANG_SIMPCHINESE} "Only installed Apps"
LangString field12 ${LANG_SIMPCHINESE} "Delete packages after Install"
LangString field13 ${LANG_SIMPCHINESE} "Location for local database"
LangString field15 ${LANG_SIMPCHINESE} "Location (http) for database (ignored if local database is set)"
LangString field17 ${LANG_SIMPCHINESE} "View Options (what pages and/or messages will be shown)"
LangString field18 ${LANG_SIMPCHINESE} "Welcome"
LangString field19 ${LANG_SIMPCHINESE} "Settings"
LangString field20 ${LANG_SIMPCHINESE} "Components"
LangString field21 ${LANG_SIMPCHINESE} "Finish"
LangString field22 ${LANG_SIMPCHINESE} "more wget options"


LangString DESC_Section1 ${LANG_SIMPCHINESE} "Self update"
LangString DESC_Section2 ${LANG_SIMPCHINESE} "the portable file archiver"
LangString DESC_Section3 ${LANG_SIMPCHINESE} "word processing made portable"
LangString DESC_Section4 ${LANG_SIMPCHINESE} "sound editing and recording to go"
LangString DESC_Section5 ${LANG_SIMPCHINESE} "extract, convert, and encode just about anywhere"
LangString DESC_Section6 ${LANG_SIMPCHINESE} "antivirus to go"
LangString DESC_Section7 ${LANG_SIMPCHINESE} "a quick link to the command line"
LangString DESC_Section8 ${LANG_SIMPCHINESE} "Lightweight, fast, easy-to-use audio player"
LangString DESC_Section9 ${LANG_SIMPCHINESE} "DOSBox emulates an Intel x86 PC, complete with sound, graphics, mouse, modem, etc., necessary for running many old DOS games"
LangString DESC_Section10 ${LANG_SIMPCHINESE} "securely erase your data"
LangString DESC_Section11 ${LANG_SIMPCHINESE} "FTP in your pocket"
LangString DESC_Section12 ${LANG_SIMPCHINESE} "your browser, your way... in your pocket™"
LangString DESC_Section13 ${LANG_SIMPCHINESE} "Image editing on the go"
LangString DESC_Section14 ${LANG_SIMPCHINESE} "take your finances with you"
LangString DESC_Section15 ${LANG_SIMPCHINESE} "CD/DVD recording on the go"
LangString DESC_Section16 ${LANG_SIMPCHINESE} "Open Source SVG Editor"
LangString DESC_Section17 ${LANG_SIMPCHINESE} "A portable puzzle to waste any amount of time"
LangString DESC_Section18 ${LANG_SIMPCHINESE} "your passwords, secured to go"
LangString DESC_Section19 ${LANG_SIMPCHINESE} "web editing on the go"
LangString DESC_Section20 ${LANG_SIMPCHINESE} "breakout-style arcade game similar to Arkanoid"
LangString DESC_Section21 ${LANG_SIMPCHINESE} "find mines on the go"
LangString DESC_Section22 ${LANG_SIMPCHINESE} "compact, portable instant messaging"
LangString DESC_Section23 ${LANG_SIMPCHINESE} "the movie player to go"
LangString DESC_Section24 ${LANG_SIMPCHINESE} "text editing to go"
LangString DESC_Section25 ${LANG_SIMPCHINESE} "a virtual keyboard to go"
LangString DESC_Section26 ${LANG_SIMPCHINESE} "the complete office suite that's completely portable"
LangString DESC_Section27 ${LANG_SIMPCHINESE} "Change your PDFs on the go"
LangString DESC_Section28 ${LANG_SIMPCHINESE} "the portable file archiver"
LangString DESC_Section29 ${LANG_SIMPCHINESE} "instant messaging made portable and secure"
LangString DESC_Section30 ${LANG_SIMPCHINESE} "stick notes to go"
LangString DESC_Section31 ${LANG_SIMPCHINESE} "texas hold-em on the go"
LangString DESC_Section32 ${LANG_SIMPCHINESE} "portable telnet and SSH"
LangString DESC_Section33 ${LANG_SIMPCHINESE} "portable puzzle fun"
LangString DESC_Section34 ${LANG_SIMPCHINESE} "the portable PDF viewer"
LangString DESC_Section35 ${LANG_SIMPCHINESE} "your calendar in your pocket, without a PDA"
LangString DESC_Section36 ${LANG_SIMPCHINESE} "keep on top of tasks, wherever you go"
LangString DESC_Section37 ${LANG_SIMPCHINESE} "real email, on the go™"
LangString DESC_Section38 ${LANG_SIMPCHINESE} "sync, backup and secure, all in one place"
LangString DESC_Section39 ${LANG_SIMPCHINESE} "video processing to go"
LangString DESC_Section40 ${LANG_SIMPCHINESE} "bringing your portable life into focus"
LangString DESC_Section41 ${LANG_SIMPCHINESE} "play your media anywhere"
LangString DESC_Section42 ${LANG_SIMPCHINESE} "know what's on your drive"
LangString DESC_Section43 ${LANG_SIMPCHINESE} "check MD5 sums on the go"
LangString DESC_Section44 ${LANG_SIMPCHINESE} "compare files on the go"
LangString DESC_Section45 ${LANG_SIMPCHINESE} "SFTP, FTP and SCP on the go"
LangString DESC_Section46 ${LANG_SIMPCHINESE} " "
LangString DESC_Section47 ${LANG_SIMPCHINESE} " "
LangString DESC_Section48 ${LANG_SIMPCHINESE} " "
LangString DESC_Section49 ${LANG_SIMPCHINESE} " "
LangString DESC_Section50 ${LANG_SIMPCHINESE} " "
LangString DESC_Section51 ${LANG_SIMPCHINESE} " "
LangString DESC_Section52 ${LANG_SIMPCHINESE} " "
LangString DESC_Section53 ${LANG_SIMPCHINESE} " "
LangString DESC_Section54 ${LANG_SIMPCHINESE} " "
LangString DESC_Section55 ${LANG_SIMPCHINESE} " "
LangString DESC_Section56 ${LANG_SIMPCHINESE} " "
LangString DESC_Section57 ${LANG_SIMPCHINESE} " "
LangString DESC_Section58 ${LANG_SIMPCHINESE} " "
LangString DESC_Section59 ${LANG_SIMPCHINESE} " "
LangString DESC_Section60 ${LANG_SIMPCHINESE} " "
LangString DESC_Section61 ${LANG_SIMPCHINESE} " "
LangString DESC_Section62 ${LANG_SIMPCHINESE} " "
LangString DESC_Section63 ${LANG_SIMPCHINESE} " "
LangString DESC_Section64 ${LANG_SIMPCHINESE} " "
LangString DESC_Section65 ${LANG_SIMPCHINESE} " "
LangString DESC_Section66 ${LANG_SIMPCHINESE} " "
LangString DESC_Section67 ${LANG_SIMPCHINESE} " "
LangString DESC_Section68 ${LANG_SIMPCHINESE} " "
LangString DESC_Section69 ${LANG_SIMPCHINESE} " "
LangString DESC_Section70 ${LANG_SIMPCHINESE} " "
LangString DESC_Section71 ${LANG_SIMPCHINESE} " "
LangString DESC_Section72 ${LANG_SIMPCHINESE} " "
LangString DESC_Section73 ${LANG_SIMPCHINESE} " "
LangString DESC_Section74 ${LANG_SIMPCHINESE} " "
LangString DESC_Section75 ${LANG_SIMPCHINESE} " "
LangString DESC_Section76 ${LANG_SIMPCHINESE} " "
LangString DESC_Section77 ${LANG_SIMPCHINESE} " "
LangString DESC_Section78 ${LANG_SIMPCHINESE} " "
LangString DESC_Section79 ${LANG_SIMPCHINESE} " "
LangString DESC_Section80 ${LANG_SIMPCHINESE} " "
LangString DESC_Section81 ${LANG_SIMPCHINESE} " "
LangString DESC_Section82 ${LANG_SIMPCHINESE} " "
LangString DESC_Section83 ${LANG_SIMPCHINESE} " "
LangString DESC_Section84 ${LANG_SIMPCHINESE} " "
LangString DESC_Section85 ${LANG_SIMPCHINESE} " "
LangString DESC_Section86 ${LANG_SIMPCHINESE} " "
LangString DESC_Section87 ${LANG_SIMPCHINESE} " "
LangString DESC_Section88 ${LANG_SIMPCHINESE} " "
LangString DESC_Section89 ${LANG_SIMPCHINESE} " "
LangString DESC_Section90 ${LANG_SIMPCHINESE} " "
LangString DESC_Section91 ${LANG_SIMPCHINESE} " "
LangString DESC_Section92 ${LANG_SIMPCHINESE} " "
LangString DESC_Section93 ${LANG_SIMPCHINESE} " "
LangString DESC_Section94 ${LANG_SIMPCHINESE} " "
LangString DESC_Section95 ${LANG_SIMPCHINESE} " "
LangString DESC_Section96 ${LANG_SIMPCHINESE} " "
LangString DESC_Section97 ${LANG_SIMPCHINESE} " "
LangString DESC_Section98 ${LANG_SIMPCHINESE} " "
LangString DESC_Section99 ${LANG_SIMPCHINESE} " "
LangString DESC_Section100 ${LANG_SIMPCHINESE} " "