/////////////////////////////////////////////////////////////////////////////
// Name:        frmprogress.h
// Purpose:     
// Author:      Steven Lamerton
// Modified by: 
// Created:     19/05/2007 21:02:05
// RCS-ID:      
// Copyright:   Copyright (C)  2006 Steven Lamerton
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), 19/05/2007 21:02:05

#ifndef _FRMPROGRESS_H_
#define _FRMPROGRESS_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "frmprogress.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_FRMPROGRESS 10036
#define ID_TEXTCTRL1 10054
#define SYMBOL_FRMPROGRESS_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX|wxDIALOG_MODAL
#define SYMBOL_FRMPROGRESS_TITLE _("Progress")
#define SYMBOL_FRMPROGRESS_IDNAME ID_FRMPROGRESS
#define SYMBOL_FRMPROGRESS_SIZE wxSize(400, 300)
#define SYMBOL_FRMPROGRESS_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * frmProgress class declaration
 */

class frmProgress: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( frmProgress )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    frmProgress();
    frmProgress( wxWindow* parent, wxWindowID id = SYMBOL_FRMPROGRESS_IDNAME, const wxString& caption = SYMBOL_FRMPROGRESS_TITLE, const wxPoint& pos = SYMBOL_FRMPROGRESS_POSITION, const wxSize& size = SYMBOL_FRMPROGRESS_SIZE, long style = SYMBOL_FRMPROGRESS_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_FRMPROGRESS_IDNAME, const wxString& caption = SYMBOL_FRMPROGRESS_TITLE, const wxPoint& pos = SYMBOL_FRMPROGRESS_POSITION, const wxSize& size = SYMBOL_FRMPROGRESS_SIZE, long style = SYMBOL_FRMPROGRESS_STYLE );

    /// Destructor
    ~frmProgress();

    /// Initialises member variables
    void Init();

    /// Creates the controls and sizers
    void CreateControls();

////@begin frmProgress event handler declarations

////@end frmProgress event handler declarations

////@begin frmProgress member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end frmProgress member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin frmProgress member variables
    wxTextCtrl* m_Progress_Text;
////@end frmProgress member variables
};

#endif
    // _FRMPROGRESS_H_
