/////////////////////////////////////////////////////////////////////////////
// Name:        frmprogress.cpp
// Purpose:     
// Author:      Steven Lamerton
// Modified by: 
// Created:     19/05/2007 21:02:04
// RCS-ID:      
// Copyright:   Copyright (C)  2006 Steven Lamerton
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), 19/05/2007 21:02:04

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma implementation "frmprogress.h"
#endif

// For compilers that support precompilation, includes "wx/wx.h".
#include "wx/wxprec.h"

#ifdef __BORLANDC__
#pragma hdrstop
#endif

#ifndef WX_PRECOMP
#include "wx/wx.h"
#endif

////@begin includes
////@end includes

#include "frmprogress.h"
#include "toucan.h"

////@begin XPM images
////@end XPM images

/*!
 * frmProgress type definition
 */

IMPLEMENT_DYNAMIC_CLASS( frmProgress, wxDialog )

/*!
 * frmProgress event table definition
 */

BEGIN_EVENT_TABLE( frmProgress, wxDialog )

////@begin frmProgress event table entries
////@end frmProgress event table entries

END_EVENT_TABLE()

/*!
 * frmProgress constructors
 */

frmProgress::frmProgress()
{
    Init();
}

frmProgress::frmProgress( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
    Init();
    Create(parent, id, caption, pos, size, style);
}

/*!
 * frmProgress creator
 */

bool frmProgress::Create( wxWindow* parent, wxWindowID id, const wxString& caption, const wxPoint& pos, const wxSize& size, long style )
{
////@begin frmProgress creation
    SetExtraStyle(wxWS_EX_BLOCK_EVENTS);
    wxDialog::Create( parent, id, caption, pos, size, style );

    CreateControls();
    if (GetSizer())
    {
        GetSizer()->SetSizeHints(this);
    }
    Centre();
////@end frmProgress creation
    return true;
}

/*!
 * frmProgress destructor
 */

frmProgress::~frmProgress()
{
////@begin frmProgress destruction
////@end frmProgress destruction
}

/*!
 * Member initialisation 
 */

void frmProgress::Init()
{
////@begin frmProgress member initialisation
    m_Progress_Text = NULL;
////@end frmProgress member initialisation
}

/*!
 * Control creation for frmProgress
 */

void frmProgress::CreateControls()
{    
////@begin frmProgress content construction
    // Generated by DialogBlocks, 20/05/2007 14:42:50 (Personal Edition)

    frmProgress* itemDialog1 = this;

    wxBoxSizer* itemBoxSizer2 = new wxBoxSizer(wxVERTICAL);
    itemDialog1->SetSizer(itemBoxSizer2);

    m_Progress_Text = new wxTextCtrl( itemDialog1, ID_TEXTCTRL1, _T(""), wxDefaultPosition, wxSize(350, 220), wxTE_MULTILINE|wxTE_READONLY|wxTE_RICH2|wxHSCROLL );
    itemBoxSizer2->Add(m_Progress_Text, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

    wxBoxSizer* itemBoxSizer4 = new wxBoxSizer(wxHORIZONTAL);
    itemBoxSizer2->Add(itemBoxSizer4, 0, wxALIGN_CENTER_HORIZONTAL|wxALL, 5);

    wxButton* itemButton5 = new wxButton( itemDialog1, wxID_OK, _("&OK"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer4->Add(itemButton5, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

    wxButton* itemButton6 = new wxButton( itemDialog1, wxID_SAVE, _("&Save"), wxDefaultPosition, wxDefaultSize, 0 );
    itemBoxSizer4->Add(itemButton6, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5);

////@end frmProgress content construction
//Working here
    wxString strFunction = wxGetApp().GetStrTemp();
}

/*!
 * Should we show tooltips?
 */

bool frmProgress::ShowToolTips()
{
    return true;
}

/*!
 * Get bitmap resources
 */

wxBitmap frmProgress::GetBitmapResource( const wxString& name )
{
    // Bitmap retrieval
////@begin frmProgress bitmap retrieval
    wxUnusedVar(name);
    return wxNullBitmap;
////@end frmProgress bitmap retrieval
}

/*!
 * Get icon resources
 */

wxIcon frmProgress::GetIconResource( const wxString& name )
{
    // Icon retrieval
////@begin frmProgress icon retrieval
    wxUnusedVar(name);
    return wxNullIcon;
////@end frmProgress icon retrieval
}
