/////////////////////////////////////////////////////////////////////////////
// Name:        frmvariable.h
// Purpose:     
// Author:      Steven Lamerton
// Modified by: 
// Created:     08/02/2007 19:08:08
// RCS-ID:      
// Copyright:   Copyright (C)  2006 Steven Lamerton
// Licence:     
/////////////////////////////////////////////////////////////////////////////

// Generated by DialogBlocks (Personal Edition), 08/02/2007 19:08:08

#ifndef _FRMVARIABLE_H_
#define _FRMVARIABLE_H_

#if defined(__GNUG__) && !defined(NO_GCC_PRAGMA)
#pragma interface "frmvariable.h"
#endif

/*!
 * Includes
 */

////@begin includes
////@end includes

/*!
 * Forward declarations
 */

////@begin forward declarations
////@end forward declarations

/*!
 * Control identifiers
 */

////@begin control identifiers
#define ID_DIALOG 10029
#define ID_COMBOBOX1 10033
#define SYMBOL_FRMVARIABLE_STYLE wxCAPTION|wxRESIZE_BORDER|wxSYSTEM_MENU|wxCLOSE_BOX
#define SYMBOL_FRMVARIABLE_TITLE _("Insert Variable")
#define SYMBOL_FRMVARIABLE_IDNAME ID_DIALOG
#define SYMBOL_FRMVARIABLE_SIZE wxSize(400, 300)
#define SYMBOL_FRMVARIABLE_POSITION wxDefaultPosition
////@end control identifiers

/*!
 * Compatibility
 */

#ifndef wxCLOSE_BOX
#define wxCLOSE_BOX 0x1000
#endif

/*!
 * frmVariable class declaration
 */

class frmVariable: public wxDialog
{    
    DECLARE_DYNAMIC_CLASS( frmVariable )
    DECLARE_EVENT_TABLE()

public:
    /// Constructors
    frmVariable( );
    frmVariable( wxWindow* parent, wxWindowID id = SYMBOL_FRMVARIABLE_IDNAME, const wxString& caption = SYMBOL_FRMVARIABLE_TITLE, const wxPoint& pos = SYMBOL_FRMVARIABLE_POSITION, const wxSize& size = SYMBOL_FRMVARIABLE_SIZE, long style = SYMBOL_FRMVARIABLE_STYLE );

    /// Creation
    bool Create( wxWindow* parent, wxWindowID id = SYMBOL_FRMVARIABLE_IDNAME, const wxString& caption = SYMBOL_FRMVARIABLE_TITLE, const wxPoint& pos = SYMBOL_FRMVARIABLE_POSITION, const wxSize& size = SYMBOL_FRMVARIABLE_SIZE, long style = SYMBOL_FRMVARIABLE_STYLE );

    /// Creates the controls and sizers
    void CreateControls();

////@begin frmVariable event handler declarations

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_OK
    void OnOkClick( wxCommandEvent& event );

    /// wxEVT_COMMAND_BUTTON_CLICKED event handler for wxID_CANCEL
    void OnCancelClick( wxCommandEvent& event );

////@end frmVariable event handler declarations

////@begin frmVariable member function declarations

    /// Retrieves bitmap resources
    wxBitmap GetBitmapResource( const wxString& name );

    /// Retrieves icon resources
    wxIcon GetIconResource( const wxString& name );
////@end frmVariable member function declarations

    /// Should we show tooltips?
    static bool ShowToolTips();

////@begin frmVariable member variables
    wxComboBox* m_List;
////@end frmVariable member variables
};

#endif
    // _FRMVARIABLE_H_
